// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKOGXkQnSI2h0J1tuE_IzFimcrc4TvqUo',
    appId: '1:658752597981:web:920fc38df7e3548853d034',
    messagingSenderId: '658752597981',
    projectId: 'the-topic-app',
    authDomain: 'the-topic-app.firebaseapp.com',
    storageBucket: 'the-topic-app.appspot.com',
    measurementId: 'G-6J0SNEKCJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL3zjmE5nytjzjrghHa5Q3WfaBAxZ8X_4',
    appId: '1:658752597981:android:35db7784e42d1ce953d034',
    messagingSenderId: '658752597981',
    projectId: 'the-topic-app',
    storageBucket: 'the-topic-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMVT0yidpNRVZP2XRfIyjkEl9EGZrZGR8',
    appId: '1:658752597981:ios:adc2d9b8074be98653d034',
    messagingSenderId: '658752597981',
    projectId: 'the-topic-app',
    storageBucket: 'the-topic-app.appspot.com',
    iosBundleId: 'com.example.topicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMVT0yidpNRVZP2XRfIyjkEl9EGZrZGR8',
    appId: '1:658752597981:ios:70fdd042bb46e34a53d034',
    messagingSenderId: '658752597981',
    projectId: 'the-topic-app',
    storageBucket: 'the-topic-app.appspot.com',
    iosBundleId: 'com.example.topicApp.RunnerTests',
  );
}
